#!/bin/bash
function getstarted() {
	if [ -n "$(cat ~/.bashrc | grep 'alias savehistory')" ];then
		echo aruyo >&2
	else
		echo "alias savehistory='history -a'" >> ~/.bashrc
	fi
}

function mysed() {
	sed -E -e 's/([0-9]{4})年([0-9]{1,2})月([0-9]{1,2})日/\1-\2-\3/g'
}

mysed "$1"


ls | sed 's/ /\n/g' | grep -E "[0-9]{4}年[0-9]{1,2}月[0-9]{1,2}日" > pakutmp.txt


exit

#init
if [ -n "$(cat ~/.bashrc | grep 'alias savehistory')" ];then
	echo aruyo >&2
else
	echo "alias savehistory='history -a'" >> ~/.bashrc
fi

# 履歴の保存を一時的に無効化
#set +o history



# historyコマンドを実行してコマンド履歴をファイルに出力
#history 2> his.txt
savehistory
tail -n 3 ~/.bash_history

# 履歴の保存を再度有効化
#set -o history
#history
#cat ~/.bash_history > his.txt

#tail -n 1 his.txt
exit
