#!/bin/bash
if [ "$1" = "-h" ]; then
	echo "This script adds a command to .bashrc"
	echo "To get more infomation, please check the source"
elif [ "$1" = "--help" ]; then
	echo "This script adds a command to .bashrc"
	echo "To get more infomation, please check the source"
fi

#getstarted
if [ -n "$(cat ~/.bashrc | grep 'alias savehistory')" ];then
	:
else
	echo "alias savehistory='history -a'" >> ~/.bashrc
fi

#current-get&rename
ls | sed 's/ /\n/g' | grep -E "^[0-9]{4}年[0-9]{1,2}月[0-9]{1,2}日" > pakutmp.txt
cat pakutmp.txt
while IFS= read -r line; do
	new=$(echo "$line" | sed -E -e 's/([0-9]{4})年([0-9]{1,2})月([0-9]{1,2})日/\1-\2-\3/g')
	mv "$line" "$new"
done < pakutmp.txt

rm pakutmp.txt
exit






# historyコマンドを実行してコマンド履歴をファイルに出力
#history 2> his.txt
savehistory
tail -n 3 ~/.bash_history

# 履歴の保存を再度有効化
#set -o history
#history
#cat ~/.bash_history > his.txt

#tail -n 1 his.txt
exit
