#!/bin/bash

function mysed() {
file="$1"
length=${#file}
for (( i=0; i<$length; i++ )); do
  case ${file:$i:1} in
    "年")
        echo -n - | sed 's/-/-/g'
        ;;
    "月")
        echo -n - | sed 's/-/-/g'
        ;;
    "日")
        ;;
    *)
        echo -n ${file:$i:1}
        ;;
  esac
done
echo
}




exit

#init
if [ -n "$(cat ~/.bashrc | grep 'alias savehistory')" ];then
	echo aruyo >&2
else
	echo "alias savehistory='history -a'" >> ~/.bashrc
fi

# 履歴の保存を一時的に無効化
#set +o history



# historyコマンドを実行してコマンド履歴をファイルに出力
#history 2> his.txt
savehistory
tail -n 3 ~/.bash_history

# 履歴の保存を再度有効化
#set -o history
#history
#cat ~/.bash_history > his.txt

#tail -n 1 his.txt
exit
