#!/bin/bash

# manual kakko kari
# input data axgumently
# outputs max

#except1
waste=$(echo -n "$2$3$4$5$6$7$8")
#opt_reading
if [ -n "$waste" ]; then
  status="error"
elif [ -n "$1" ]; then
  status='file'
else
  status='pipe'
fi
#echo $status
#status-Error
if [ "$status" == "error" ]; then
  echo "[Error!]"
  exit
else
  :
fi

#file-mode=>pipe
if [ "$status" == "file" ]; then
  max=0
  num=0
  while IFS= read -r line; do

    if [ "$line" -gt "$max" ]; then
      max="$line"
    fi

    if [[ $num =~ [1-9]000 ]]; then
      echo "$num"
    fi

    ((num++))

  done < "$1"
  echo "$max"
fi

if [ "$status" == "pipe" ]; then
  max=0
  num=0
  while IFS= read -r line; do

    if [ "$line" -gt "$max" ]; then
      max="$line"
    fi

    if [[ $num =~ [1-9]000 ]]; then
      echo "$num"
    fi

    ((num++))

  done
  echo "$max"
fi

exit
