#!/bin/bash

# manual kakko kari
# input data
# output max,min

#read filename
filename="test"
num=1
ma=-1000
mi=1000

while IFS= read -r line; do
#  echo $line
  dni=$(echo "$line" | cut -d',' -f2 | tr -d "0." | tr -d "." )
  dni=$((dni))

  if [ "$dni" -gt "$ma" ]; then
    ma="$dni"
#    echo $ma
  fi

  if [ "$dni" -lt "$mi" ]; then
    mi="$dni"
#    echo $mi
  fi

  if [[ $num =~ [1-9][0-9]000 ]] || [[ $num =~ [1-9]000 ]]; then
    echo "$num" >&2
  fi
((num++))

done < "$filename"

echo $ma > max
echo $mi > min

cat max
cat min

exit
