#!/bin/bash

if [ $# = 3 ]; then
    i=1
    while [ $i -le 18 ]; do echo -n "$1" 
    i=$((i + 1)) ; done
    i=1
    while [ $i -le 9 ]; do echo -n "$2" 
    i=$((i + 1)) ; done
    i=1
    while [ $i -le 18 ]; do echo -n "$3" 
    i=$((i + 1)) ; done
    echo
    echo -e "大変申し訳御座いません。\n厳しく改善指導いたします"
    echo -e "大変申し訳御座いません。\n即指導いたします。"
    echo -e "大変申し訳御座いません。\n指導徹底いたします"
    
elif [ $# = 6 ]; then
    i=1
    while [ $i -le 18 ]; do echo -n "$1" 
    i=$((i + 1)) ; done
    i=1
    while [ $i -le 9 ]; do echo -n "$2" 
    i=$((i + 1)) ; done
    i=1
    while [ $i -le 18 ]; do echo -n "$3" 
    i=$((i + 1)) ; done
    echo
    echo "$4"
    echo "$5"
    echo "$6"

elif [ $# = 4 ]; then
    case "$1" in
    -l|--line)

    echo -n > bmtmp
    i=1
    while [ $i -le 18 ]; do echo -n "$2" >> bmtmp
    i=$((i + 1)) ; done
    i=1
    while [ $i -le 9 ]; do echo -n "$3" >> bmtmp
    i=$((i + 1)) ; done
    i=1
    while [ $i -le 18 ]; do echo -n "$4" >> bmtmp
    i=$((i + 1)) ; done

    echo "├──────────────────────────────────┐"

    content=$(cat bmtmp)
    length=${#content}
    i=0
    c=1
    while [ $i -lt $length ]; do

        case $c in
            1)
            echo -n "│${content:$i:1}"
            ((++c))
            ;;

            2|3|4|5|6|7|8|9|10|11|12|13|14|15|16)
            echo -n ${content:$i:1}
            ((++c))
            ;;

            17)
            echo "${content:$i:1}│"
            c=1
            ;;
        esac
        ((++i))
    done
    echo "　　　　　　　　　　　　│"
    echo "└──────────────────────────────────┘"

    echo
    echo "├──────────────────────────┐"
    echo "│大変申し訳御座いません。　│
│厳しく改善指導いたします。│"
    echo "└──────────────────────────┘"
    echo
    echo "├────────────────────────┐"
    echo "│大変申し訳御座いません。│
│即指導いたします。　　　│"
    echo "└────────────────────────┘"
    echo
    echo "├────────────────────────┐"
    echo "│大変申し訳御座いません。│
│指導徹底いたします。　　│"
    echo "└────────────────────────┘"

    rm bmtmp
    esac
else
    echo "error!"
fi
exit 0